# Generated by Django 2.0 on 2018-05-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenant',
            name='adresse_mail',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='id_domaine',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='id_ecole',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='intervenant_description',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='intervenant_prenom',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='photo_de_profil',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='table_fichier',
        ),
    ]
