# Generated by Django 2.0.5 on 2018-05-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20180509_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaineecole',
            name='id_domaine',
        ),
        migrations.RemoveField(
            model_name='domaineecole',
            name='id_ecole',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_intervenant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_postulant',
        ),
        migrations.RemoveField(
            model_name='motdepasse',
            name='id_postulant',
        ),
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_adresse',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_prenom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='intervenant_nom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Domaine',
        ),
        migrations.DeleteModel(
            name='DomaineEcole',
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MotdePasse',
        ),
        migrations.DeleteModel(
            name='Postulant',
        ),
    ]
