# Generated by Django 2.0.5 on 2018-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20180510_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
