# Generated by Django 2.0.5 on 2018-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_intervenant_intervenant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_passwordConfirmation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
