# Generated by Django 2.0 on 2018-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_auto_20180511_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecoles',
            fields=[
                ('ecole_nom', models.CharField(default='', max_length=200)),
                ('id_ecole', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='intervenants',
            name='ecole_nom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
