# Generated by Django 2.0 on 2018-05-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscription', '0008_auto_20180515_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervenant_date', models.CharField(default='', max_length=10)),
                ('intervenant_avatar', models.ImageField(upload_to='photos/profil/')),
                ('intervenant_certificat', models.ImageField(upload_to='photos/certificat/')),
                ('intervenant_description', models.TextField(default='')),
                ('intervenant_nomEcole', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postulant_date', models.CharField(default='', max_length=10)),
                ('postulant_avatar', models.ImageField(upload_to='photos/')),
                ('postulant_description', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='intervenants',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postulant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Intervenants',
        ),
        migrations.DeleteModel(
            name='Postulant',
        ),
    ]
