# Generated by Django 2.0.5 on 2018-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_auto_20180516_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenantes',
            name='intervenant_avatar',
            field=models.ImageField(default='photos/profil/grosse.jpeg', upload_to='photos/profil/'),
        ),
        migrations.AlterField(
            model_name='postulants',
            name='postulant_avatar',
            field=models.ImageField(default='photos/profil/grosse.jpeg', upload_to='photos/'),
        ),
    ]
