# Generated by Django 2.0 on 2018-05-25 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscription', '0010_auto_20180525_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversationssss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postulant_date', models.CharField(default='', max_length=10)),
                ('postulant_avatar', models.ImageField(default='photos/profil/grosse.jpeg', upload_to='photos/')),
                ('postulant_description', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
