# Generated by Django 2.0 on 2018-05-25 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_auto_20180525_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationssss',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de envoie'),
        ),
    ]
