# Generated by Django 2.1.dev20180502132004 on 2018-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0014_auto_20180527_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenantes',
            name='intervenant_avatar',
            field=models.ImageField(default='photos/profil/profile.jpg', upload_to='photos/profil/'),
        ),
        migrations.AlterField(
            model_name='postulants',
            name='postulant_avatar',
            field=models.ImageField(default='photos/profil/profile.jpg', upload_to='photos/'),
        ),
    ]
